# Generated by Django 4.1.3 on 2022-11-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('author', models.CharField(blank=True, max_length=110, null=True)),
                ('your_name', models.CharField(blank=True, max_length=110, null=True)),
                ('your_lastname', models.CharField(blank=True, max_length=110, null=True)),
                ('your_university', models.CharField(blank=True, max_length=110, null=True)),
                ('your_college', models.CharField(blank=True, max_length=110, null=True)),
                ('detail', models.CharField(blank=True, max_length=110, null=True)),
                ('you_are', models.CharField(blank=True, choices=[('buyer', 'buyer'), ('seller', 'seller')], max_length=110, null=True)),
            ],
        ),
    ]
