# Generated by Django 4.1.3 on 2022-11-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tel_id',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
