# Generated by Django 4.1.3 on 2022-11-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swbooks', '0002_book_tel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='bookname',
        ),
    ]
